version: 2
jobs:
  build:
    working_directory: ~/app
    environment:
    docker:
      -image: circleci/node:12.18.0
    steps:
      - checkout
      - run:
          name: install npm
          command: npm install
      - run:
          name: build
          command: npm run build
      - run:
          name: install npm
          command: npm install