version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.18.0
    working_directory: ~/app
    environment:
    steps: 
      - checkout
      - run:
          name: install npm
          command: npm install
      - run:
          name: build
          command: npm run build
      - run:
          name: install npm
          command: npm install
      - store_artifact: 
          path : ~/app/build